version: 0.1
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "BUILD STARTED"
      - python manage.py collectstatic --noinput
      - echo "BUILD COMPLETE"
artifacts:
   files:
    - '**/*'
